package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Publisher;
import org.mybatis.cdi.Mapper;


@Mapper
public interface PublisherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PUBLISHER
     *
     * @mbg.generated Thu Mar 31 12:26:10 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PUBLISHER
     *
     * @mbg.generated Thu Mar 31 12:26:10 EEST 2022
     */
    int insert(Publisher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PUBLISHER
     *
     * @mbg.generated Thu Mar 31 12:26:10 EEST 2022
     */
    Publisher selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PUBLISHER
     *
     * @mbg.generated Thu Mar 31 12:26:10 EEST 2022
     */
    List<Publisher> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PUBLISHER
     *
     * @mbg.generated Thu Mar 31 12:26:10 EEST 2022
     */
    int updateByPrimaryKey(Publisher record);
}